[project]
name = "kryon"
version = "1.0.0"

[plugins]

[plugins.animations]
enabled = true
required = true   # Animation functionality requires this plugin
path = "../kryon-plugins/animations/build/libkryon_animations.so"
