[package]
name = "kryon-macros"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "Procedural macros for Kryon UI framework"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["visit", "full"] }
quote = "1.0"
proc-macro2 = "1.0"
